### ISSUE TITLE
Small issue about comment in add user component

### ISSUE THREAD

**Issue by OllieWillette667** [UMM-CSci-3601/3601-lab4-mongo#42]
In add-user.component.html the first line is a commment, with a link to 
https://github.com/AngularTemplates/angular-forms-and-validations/blob/master/src/app/form-component/form.component.html
which 404's. But I think this is what it should be replaced with.
https://github.com/AngularTemplates/angular-forms-and-validations/blob/master/src/app/forms/forms.component.html

**Comment by kklamberty** [comment]
Thanks for pointing this out! At this time, it does not seem to be included in our file anymore. I'm going to close this issue, but your help is still appreciated.
