### ISSUE TITLE
Fix case insensitive queries so they are actually case insensitive

### ISSUE THREAD

**Issue by NicMcPhee** [UMM-CSci-3601/3601-lab4-mongo#43]
Our case insensitive queries in the example `UserController` code aren't actually case insensitive, which came as a non-trivial surprise this semester. Despite what lots of things say on this Internet, adding `"i"` as a `Pattern` property like this:

```java
      filters.add(regex(COMPANY_KEY,  Pattern.quote(ctx.queryParam(COMPANY_KEY)), "i"));
```

doesn't actually work.

@miiiiip did some digging and shared a solution on Slack, which is to add a `?` in front of the `i`:

```java
      filters.add(regex(COMPANY_KEY,  Pattern.quote(ctx.queryParam(COMPANY_KEY)), "?i"));
```

I honestly don't get why we need `"?i"` instead of just `"i"`, but I'm sure it's in some documentation somewhere.

I also tried using the `Pattern.CASE_INSENSITIVE`, but never got that to work. I was pushing pretty fast, though, so it might be worth revisiting that. [This post on "Case-insensitive string matching in Java"](https://www.baeldung.com/java-case-insensitive-string-matching) might be a useful resource.

This also should be applied to [the iteration template](https://github.com/UMM-CSci-3601/3601-iteration-template/issues/793).

**Comment by NicMcPhee** [comment]
So I think the problem is that we were basically just adding `i` to the search string, and we needed what they call an "embedded flag expression `(?i)`" to indicate that we were changing "modes" to use case-insensitive searching. Apparently you can do fancy stuff with that to change case-sensitivity locally in subsets of a pattern.

TBH, I think the better solution for us is to use the `CASE_INSENSITIVE` when we compile the `Pattern` rather than futzing about with the rather obscure `(?i)` notation. [The Oracle Java docs cover this in a fairly reasonable way](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/regex/Pattern.html#CASE_INSENSITIVE).

**Comment by kklamberty** [comment]
@NicMcPhee - There doesn't seem to be a regex for company name on the server size. Do you mean that when things are taken from the interface you want to ignore case in the process of making the query? I don't know what to look for to know if you already addressed the part you said about "when we compile the Pattern". Thanks!

**Comment by NicMcPhee** [comment]
Sorry – it wasn't super obvious where the issue was. [In `UserController::getUsers()`](https://github.com/UMM-CSci-3601/3601-lab4-mongo/blob/2fdd596e2bd7910e1b9f9ffae382ee1ca729bb15/server/src/main/java/umm3601/user/UserController.java#L96), for example, we have:

```java
    if (ctx.queryParamMap().containsKey(COMPANY_KEY)) {
      filters.add(regex(COMPANY_KEY,  Pattern.quote(ctx.queryParam(COMPANY_KEY)), "i"));
    }
```

Adding the `"i"` to this was in theory supposed to make the query case insensitive, but it doesn't.

**Comment by kklamberty** [comment]
What about something like this:
```typescript
    if (ctx.queryParamMap().containsKey(COMPANY_KEY)) {
      Pattern pattern = Pattern.compile(ctx.queryParam(COMPANY_KEY), Pattern.CASE_INSENSITIVE);
      filters.add(regex(COMPANY_KEY, pattern));
    }
```
I think this solution takes the mystery out of what the "i" was about (like you said earlier might be better), and I'm wondering if we were missing a Pattern.compile method that was needed, and that was causing the problem. [This explanation](https://stackoverflow.com/questions/15409296/what-is-the-use-of-pattern-quote-method) leaves me to believe that Pattern.quote was not returning a Pattern, and that might have been our problem. Incidentally, it might also explain why I didn't know where to look for where we compile the pattern... because we didn't.

Was there a failing test we could use to capture the described problem? This passes our checks, but I'm not sure I totally understand the bug, and I don't know if it would show up in e2e or is we compensate for the case (in)sensitivity elsewhere that would mask a problem if it still existed here.

**Comment by NicMcPhee** [comment]
That could do the trick! I don't think I realized that `Pattern.compile()` needed to be used.

I don't think there's a test that failed because of the problem (bad me). I think that if you start up the server and send it a `GET` request with part of a company name in lower case (like `"ohm"`), then I think you get nothing back with the old code.

**Comment by NicMcPhee** [comment]
As noted in the discussion of #54, this seems to have magically fixed itself. I'm not sure how, but we'll take the win and close this issue.
